#!/bin/bash -e
clear
echo "============================================"
echo "WordPress Install Script"
echo "============================================"
echo "Database Name: "
read -e dbname
echo "Database User: "
read -e dbuser
echo "Database Password: "
read -s dbpass
echo "run install? (y/n)"
read -e run
if [ "$run" == n ] ; then
exit
else
echo "============================================"
echo "Now installing WordPress for you."
echo "============================================"
#### Update the OS before installing applications
sudo yum update -y
#Download and install wget for downloading packages from Internet
sudo yum install wget –y
#Download Apache server and ssl dependencies for loading all websites.  
sudo yum install httpd -y
sudo yum install mod_ssl -y
sudo yum install openssl –y
#Enable Webserver 
sudo systemctl start httpd
sudo systemctl enable httpd
###Enable firewall to be configured for the appropriate ports. 
sudo firewall-cmd --zone=public --add-port=80/tcp —-permanent
sudo firewall-cmd --zone=public --add-port=443/tcp —-permanent
sudo firewall-cmd --reload
sudo yum install php php-mysql -y
sudo yum install php-pdo php-gd php-xml –y
sudo systemctl restart httpd
sudo yum install mysql-server –y
sudo systemctl start mysqld
sudo systemctl enable mysqld

#Download wordpress
sudo wget -P /var/www/html/ https://wordpress.org/latest.tar.gz
#sudo curl -o /var/www/html/ https://wordpress.org/latest.tar.gz
#unzip wordpress
cd /var/www/html/
sudo tar -zxvf latest.tar.gz
sudo chown -R apache:apache /var/www/html/*
#change dir to wordpress
cd wordpress
#copy file to parent dir
sudo cp -rf . ..
#move back to parent dir
cd ..
#remove files from wordpress folder
sudo rm -R wordpress
#create wp config
sudo cp wp-config-sample.php wp-config.php
#set database details with perl find and replace
sudo perl -pi -e "s/database_name_here/$dbname/g" wp-config.php
sudo perl -pi -e "s/username_here/$dbuser/g" wp-config.php
sudo perl -pi -e "s/password_here/$dbpass/g" wp-config.php

#create uploads folder and set permissions
sudo mkdir wp-content/uploads
sudo chmod 775 wp-content/uploads
echo "Cleaning..."
#remove zip file
sudo rm latest.tar.gz
echo "========================="
echo "Installation is complete."
echo "========================="
fi

